import React, { useEffect, useState } from 'react';
import PropTypes from 'prop-types';

import { formatMessage } from 'utils/i18n';

import styles from './ArticleToc.module.scss';

// The desktop rail can be folded away, leaving nothing behind but the fold
// button itself. The choice is remembered so a reader who wants the article at
// full width folds it once, not per post.
const COLLAPSED_STORAGE_KEY = 'tocCollapsed';

/**
 * Article outline: the desktop rail stays visible, while this same outline can
 * open as a large reading surface on every viewport. The HTML is generated by
 * `lib/toc.js`, so the heading anchors remain the single source of truth.
 */
const ArticleToc = function ({ tableOfContents }) {
    const [open, setOpen] = useState(false);
    const [collapsed, setCollapsed] = useState(false);
    const tOutline = formatMessage('tArticleOutline');
    const tOpenOutline = formatMessage('tOpenOutline');
    const tCloseOutline = formatMessage('tCloseOutline');
    const tCollapseOutline = formatMessage('tCollapseOutline');
    const tExpandOutline = formatMessage('tExpandOutline');

    useEffect(() => {
        setCollapsed(window.localStorage.getItem(COLLAPSED_STORAGE_KEY) === '1');
    }, []);

    useEffect(() => {
        if (!open) return undefined;

        const onKeyDown = (event) => {
            if (event.key === 'Escape') setOpen(false);
        };
        const previousOverflow = document.body.style.overflow;
        document.body.style.overflow = 'hidden';
        document.addEventListener('keydown', onKeyDown);

        return () => {
            document.body.style.overflow = previousOverflow;
            document.removeEventListener('keydown', onKeyDown);
        };
    }, [open]);

    if (!tableOfContents) return null;

    const closeAfterJump = (event) => {
        if (event.target.closest('a')) setOpen(false);
    };

    const toggleCollapsed = () => {
        const next = !collapsed;
        setCollapsed(next);
        window.localStorage.setItem(COLLAPSED_STORAGE_KEY, next ? '1' : '0');
    };

    return (
        <>
            <aside
                className={`${styles['toc-rail']} css-toc ${
                    collapsed ? styles['toc-rail-collapsed'] : ''
                }`}
                aria-label={tOutline}
            >
                <div className={styles['toc-rail-heading']}>
                    <span className={styles['toc-rail-label']}>{tOutline}</span>
                    <div className={styles['toc-rail-actions']}>
                        <button
                            type="button"
                            className={styles['toc-expand']}
                            onClick={() => setOpen(true)}
                            aria-label={tOpenOutline}
                            title={tOpenOutline}
                        >
                            <span className={styles['toc-expand-icon']} aria-hidden="true">
                                <span />
                                <span />
                                <span />
                                <span />
                            </span>
                        </button>
                        <button
                            type="button"
                            className={styles['toc-collapse']}
                            onClick={toggleCollapsed}
                            aria-expanded={!collapsed}
                            aria-controls="toc-rail-body"
                            aria-label={collapsed ? tExpandOutline : tCollapseOutline}
                            title={collapsed ? tExpandOutline : tCollapseOutline}
                        >
                            <span className={styles['toc-collapse-icon']} aria-hidden="true" />
                        </button>
                    </div>
                </div>
                <div
                    id="toc-rail-body"
                    className={styles['toc-rail-body']}
                    dangerouslySetInnerHTML={{ __html: tableOfContents }}
                />
            </aside>

            <button
                type="button"
                className={styles['toc-open-button']}
                onClick={() => setOpen(true)}
                aria-label={tOpenOutline}
                title={tOpenOutline}
            >
                <span className={styles['toc-open-icon']} aria-hidden="true">
                    <span />
                    <span />
                    <span />
                </span>
                <span>{tOutline}</span>
            </button>

            <div
                className={`${styles['toc-modal-layer']} ${
                    open ? styles['toc-modal-layer-open'] : ''
                }`}
                role="presentation"
                aria-hidden={!open}
            >
                    <button
                        type="button"
                        className={styles['toc-backdrop']}
                        onClick={() => setOpen(false)}
                        aria-label={tCloseOutline}
                    />
                    <section
                        className={`${styles['toc-modal']} css-toc-modal`}
                        role="dialog"
                        aria-modal="true"
                        aria-label={tOutline}
                        onClick={closeAfterJump}
                    >
                        <header className={styles['toc-modal-header']}>
                            <div>
                                <p className={styles['toc-kicker']}>anyspace</p>
                                <h2>{tOutline}</h2>
                            </div>
                            <button
                                type="button"
                                className={styles['toc-close']}
                                onClick={() => setOpen(false)}
                                aria-label={tCloseOutline}
                                title={tCloseOutline}
                            >
                                <span aria-hidden="true">×</span>
                            </button>
                        </header>
                        <div
                            className={styles['toc-modal-content']}
                            dangerouslySetInnerHTML={{ __html: tableOfContents }}
                        />
                    </section>
            </div>
        </>
    );
};

ArticleToc.propTypes = {
    tableOfContents: PropTypes.string.isRequired,
};

export default ArticleToc;
