import React, { useEffect, useState } from 'react';
import PropTypes from 'prop-types';

import { formatMessage } from 'utils/i18n';

import styles from './ArticleToc.module.scss';

/**
 * Article outline: the desktop rail stays visible, while this same outline can
 * open as a large reading surface on every viewport. The HTML is generated by
 * `lib/toc.js`, so the heading anchors remain the single source of truth.
 */
const ArticleToc = function ({ tableOfContents }) {
    const [open, setOpen] = useState(false);
    const tOutline = formatMessage('tArticleOutline');
    const tOpenOutline = formatMessage('tOpenOutline');
    const tCloseOutline = formatMessage('tCloseOutline');

    useEffect(() => {
        if (!open) return undefined;

        const onKeyDown = (event) => {
            if (event.key === 'Escape') setOpen(false);
        };
        const previousOverflow = document.body.style.overflow;
        document.body.style.overflow = 'hidden';
        document.addEventListener('keydown', onKeyDown);

        return () => {
            document.body.style.overflow = previousOverflow;
            document.removeEventListener('keydown', onKeyDown);
        };
    }, [open]);

    if (!tableOfContents) return null;

    const closeAfterJump = (event) => {
        if (event.target.closest('a')) setOpen(false);
    };

    return (
        <>
            <aside className={`${styles['toc-rail']} css-toc`} aria-label={tOutline}>
                <div className={styles['toc-rail-heading']}>
                    <span>{tOutline}</span>
                    <button
                        type="button"
                        className={styles['toc-expand']}
                        onClick={() => setOpen(true)}
                        aria-label={tOpenOutline}
                        title={tOpenOutline}
                    >
                        <span aria-hidden="true">↗</span>
                    </button>
                </div>
                <div dangerouslySetInnerHTML={{ __html: tableOfContents }} />
            </aside>

            <button
                type="button"
                className={styles['toc-open-button']}
                onClick={() => setOpen(true)}
                aria-label={tOpenOutline}
                title={tOpenOutline}
            >
                <span className={styles['toc-open-icon']} aria-hidden="true">
                    <span />
                    <span />
                    <span />
                </span>
                <span>{tOutline}</span>
            </button>

            <div
                className={`${styles['toc-modal-layer']} ${
                    open ? styles['toc-modal-layer-open'] : ''
                }`}
                role="presentation"
                aria-hidden={!open}
            >
                    <button
                        type="button"
                        className={styles['toc-backdrop']}
                        onClick={() => setOpen(false)}
                        aria-label={tCloseOutline}
                    />
                    <section
                        className={`${styles['toc-modal']} css-toc-modal`}
                        role="dialog"
                        aria-modal="true"
                        aria-label={tOutline}
                        onClick={closeAfterJump}
                    >
                        <header className={styles['toc-modal-header']}>
                            <div>
                                <p className={styles['toc-kicker']}>anyspace</p>
                                <h2>{tOutline}</h2>
                            </div>
                            <button
                                type="button"
                                className={styles['toc-close']}
                                onClick={() => setOpen(false)}
                                aria-label={tCloseOutline}
                                title={tCloseOutline}
                            >
                                <span aria-hidden="true">×</span>
                            </button>
                        </header>
                        <div
                            className={styles['toc-modal-content']}
                            dangerouslySetInnerHTML={{ __html: tableOfContents }}
                        />
                    </section>
            </div>
        </>
    );
};

ArticleToc.propTypes = {
    tableOfContents: PropTypes.string.isRequired,
};

export default ArticleToc;
